### ISSUE TITLE
Respond with password validation errors in the api when creating a user.

### ISSUE THREAD

**Issue by italoantonio0909** [HackSoftware/Styleguide-Example#13]
Hi I am using the style guide, I find it interesting to be able to separate the concerns.
When I perform a user registration and enter a weak password, the error messages from the api are not sent.
So how can I perform this validation? In the service?
Help please, am I following this example guide?

**Comment by RadoRado** [comment]
@italoantonio0909 Hello :wave: 

Can you provide some kind of a code example, so we can help?

If you want to trigger validation, based on a model, to be returned from the API, please check the https://github.com/HackSoftware/Django-Styleguide#exception-handling examples here.

If you provide an example, we'll be able to help out more.

Cheers!

**Comment by italoantonio0909** [comment]
Hello @RadoRado 
I will explain in details, thank you for your answer.

I am implementing an authentication module based on the style guide you provide

When using the sample user creation service in the guide, ignore password validations as AbstractBaseUser raises exceptions when validating these fields, such as length and common password.

#user.services.py
def user_create(
    *,
    first_name: str,
    last_name: str,
    email: str,
    is_active: bool = True,
    is_admin: bool = False,
    password: Optional[str] = None
    ) -> BaseUser:

    user = BaseUser.objects.create_user(
        first_name=first_name,
        last_name=last_name,
        email=email,
        is_active=is_active,
        is_admin=is_admin,
        password=password,
    )

    #Send notification create account
    user_create_notify(user_email=email)

    return user


My question is that if the following form is correct throwing exceptions, since a service maintains all the business logic, if I want to increase its validations, everything I do in the service?
Note: I am strictly following the style guide


#user.services.py
def user_create(
    *,
    first_name: str,
    last_name: str,
    email: str,
    is_active: bool = True,
    is_admin: bool = False,
    password: Optional[str] = None
    ) -> BaseUser:
    
    errors = dict()
    try:
        # Validate the password and username and catch the exception
        validators.validate_password(password=password, user=email)

    # The exception raised here is different than serializers.ValidationError
    except Exception as e:
        errors['password'] = list(e.messages)

    if errors:
        raise ValidationError(errors)

    user = BaseUser.objects.create_user(
        first_name=first_name,
        last_name=last_name,
        email=email,
        is_active=is_active,
        is_admin=is_admin,
        password=password,
    )

    #Send notification create account
    user_create_notify(user_email=email)

    return user



Thank you for taking the time to answer my question.

**Comment by RadoRado** [comment]
@italoantonio0909

If you want to have this general pattern:

1. Service tries doing something
2. There's some kind of an error in validation
3. Raise `ValidationError` - I'd recommend sticking with `core.django.exceptions.ValidationError`, not to leak DRF into your service layer (although, it might not be that bad) 
4. Your API layer should know how to handle that. We've described our way of handling it here - https://github.com/HackSoftware/Django-Styleguide#exception-handling - but you might just do a `try/except` around your service call & do something else.

Again, the general idea of the styleguide is to have a separation of concerns between your API layer & your business logic / models.

Let me know if that answer is actually helpful.

**Comment by italoantonio0909** [comment]
of course if I have separate logic.
Check pl
https://github.com/italoantonio0909/ecommerce_django/blob/master/ecommerce/users/services.py

**Comment by RadoRado** [comment]
@italoantonio0909 Apologies for answering that late.

The link above is giving me 404.

If you need anything in addition from me, feel free to reopen the issue :v:
